### ISSUE TITLE
pull-to-refresh is still enabled regardless of overscroll-behavior - chrome iOS

### ISSUE THREAD

**Issue by mkralla11** [ebidel/demos#6]
*Expected:*
```
html, body{
  overscroll-behavior: none;
  position: fixed;
  overflow: hidden;
}
```
Applying the styles above should disable pull-to-refresh.

*Actual:*
pull-to-refresh still occurs. See video below.

*Verions*:
iOS (currently latest): 11.2.6
Chrome: 65.0.3325.152

![pull_to_refresh_issue](https://user-images.githubusercontent.com/2223901/38525654-1b8a914a-3c21-11e8-8f31-492bb8d28490.gif)

**Comment by mkralla11** [comment]
Hey Eric, if this is the wrong place to log this issue, please point me to the correct page and I will move it to the right place. I saw your demos (and the fact that you work for Google) and I thought, "this engineer seems important." 😄 Thank you in advance!

**Comment by ebidel** [comment]
:) Thanks. I think this boils down to the fact that Chrome on iOS is not really Chrome. It's rendering engine is actually Webkit/Safari, which doesn't support CSS `overflow-scroll-behavior` quite yet:

https://caniuse.com/#feat=css-overscroll-behavior

**Comment by mkralla11** [comment]
Yeah I did read that, was hoping it wasn’t the root cause 😂, thanks anyway though! I’ll have to stick with my current implementation  with touchmove and preventDefault.

**Comment by jsgiant** [comment]
I too got the same issue as @mkralla11  mentioned above. @ebidel   Is this issue fixed or is there any other way to resolve this, Let me know if any! Thanks in advance.
